name: build & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install project
      run: |
        make install
    - name: Run lint
      run: |
        make lint
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Run tests
      uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: task_manager.settings
      with:
        coverageCommand: make test

